sudo: required
dist: trusty

# Caching so the next build will be fast too.
cache:
  directories:
    - $HOME/.stack

env:
  global:
    - LLVM_VERSION=3.5.0
    - LLVM_ARCHIVE_PATH=$HOME/clang+llvm.tar.xz

before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - export PATH=/opt/ghc/7.10.2/bin:$PATH

  # LLVM
  - wget http://llvm.org/releases/$LLVM_VERSION/clang+llvm-$LLVM_VERSION-x86_64-linux-gnu-ubuntu-14.04.tar.xz -O $LLVM_ARCHIVE_PATH
  - mkdir $HOME/clang+llvm
  - tar xf $LLVM_ARCHIVE_PATH -C $HOME/clang+llvm --strip-components 1
  - export PATH=$HOME/clang+llvm/bin:$PATH

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - ghc-7.10.2
    - libedit-dev

script:
  - stack --no-terminal --skip-ghc-check test
